name: Export iOS IPA

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Resolve Swift packages
        run: |
          xcodebuild \
            -project maciOS.xcodeproj \
            -scheme maciOS \
            -resolvePackageDependencies

      - name: Build AppKit-iOS
        run: |
          CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM="" xcodebuild \
            -project AppKit/AppKit-iOS.xcodeproj \
            -scheme AppKit-iOS \
            -sdk iphoneos clean build

      - name: Archive app
        run: |
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM="" xcodebuild \
            -project maciOS.xcodeproj \
            -scheme maciOS \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/maciOS.xcarchive \
            clean archive

      - name: Upload xcarchive
        uses: actions/upload-artifact@v4
        with:
          name: maciOS-xcarchive
          path: build/maciOS.xcarchive
